Case Scenario: You are working as a Senior Data Scientist at a Klavi a firm specialized in credit risk. A Fintech Client wants to review their credit granting policy and needs to define:

 Which variables are most relevant for predicting default

 Which variables are good candidates for a practical credit policy (rules + score)

 How to turn these variables into an objective and justifiable proposal for the business team


 Challenge: You are given one week to analyze the data files provided by the client. You must deliver a recommendation on how to proceed using Klavi’s variables. Using a visual approach, show how to analyze the data and extract meaningful business insights.

Please detail:
 The main steps you would take to explore, clean, and organize the provided dataset.
 The key factors or criteria you would consider essential to ensure the insights are relevant, accurate, and representative.
 How you would validate both the analytical approach and the insights generated.

Please fell free to contact Andrea Filgueiras at andrea.filgueiras@klavi.ai if you have any questions

In [1]:
import pandas as pd
import numpy as np

In [7]:
base_profile = pd.read_parquet("./profile_case_credit.parquet")

base_transactions = pd.read_parquet("./transactions_case_credit.parquet")

In [8]:
base_transactions.head(5)

,uuid,REFERENCIA,score_klavi_1,score_klavi_2,classe_social,status_empregaticio,regiao,Renda,risco_aposta,Capacidade Financeira
0,7b0c9b36fe0f730f7c0d081534ff9a2b,2024-06-12,58.07,512.0,D/E,Desconhecido,Sudeste,1052.65,0.0,839.64
3,513b46119c7d33fc324f3c561905c159,2025-02-06,NaN,422.0,C,Desconhecido,Sudeste,NaN,NaN,2213.37
7,0d7fed4a5b92cbae24e2b80e49fb0a4e,2025-06-13,NaN,607.0,C,Desconhecido,Sudeste,NaN,NaN,587.04
8,c158eeca94b81f5f63cee1496dbea081,2024-07-30,NaN,NaN,C,Autônomo,Sudeste,NaN,NaN,1961.59
9,97ebff4ac03d546fcb03040d1866bea0,2024-11-04,NaN,533.0,B,Desconhecido,Sudeste,NaN,NaN,3585.16

In [9]:
base_transactions.describe()

,score_klavi_1,score_klavi_2,Renda,risco_aposta,Capacidade Financeira
count,32277.000000,331573.000000,32277.000000,32277.000000,3.252860e+05
mean,-72475.672167,520.963981,2850.452457,1.412585,1.925911e+03
std,259379.346501,60.696365,3600.016877,2.739815,5.038808e+03
min,-999999.000000,345.000000,317.280000,0.000000,-1.088145e+06
25%,40.340000,481.000000,1321.570000,0.000000,8.038300e+02
50%,57.250000,524.000000,2066.940000,0.000000,1.470810e+03
75%,68.190000,566.000000,3057.770000,1.000000,2.361590e+03
max,100.000000,663.000000,129296.190000,10.000000,1.207959e+05

In [4]:
base_profile.columns

Index(['uuid', 'DATA', 'SAFRA', 'OVER30M2', 'STATUS'], dtype='str')

In [6]:
base_profile.head(5)

,uuid,DATA,SAFRA,OVER30M2,STATUS
0,d946dabe8351c29c3ca9db3c7005341b,2024-08-24,202408.0,0.0,Contratado
1,b9aa3d3552e2e21f92d34df2540de5c3,2024-09-02,202409.0,1.0,Contratado
2,ac5371c706da6f7a57c9b9593a8a5d04,2024-11-25,202411.0,0.0,Contratado
3,d44880bed90eaacb2fba3feead83ca16,2024-09-09,202409.0,0.0,Contratado
4,8ec0eefeda7ae58d5a98a2d59aca4bbb,2024-06-18,202406.0,0.0,Contratado

In [3]:
base_profile.describe()

               SAFRA      OVER30M2
count  220618.000000  24148.000000
mean   202450.283331      0.103031
std        46.821529      0.304006
min    202406.000000      0.000000
25%    202409.000000      0.000000
50%    202412.000000      0.000000
75%    202503.000000      0.000000
max    202506.000000      1.000000